apiVersion: v2
name: directus
type: application

description: |
  A Helm chart for installing Directus on Kubernetes.
  Directus is a real-time API and App dashboard for managing SQL database content.

home: https://directus.io/

sources:
  - https://github.com/directus-labs/helm-chart/tree/master/charts/directus
  - https://github.com/directus/directus

icon: https://avatars.githubusercontent.com/u/79210894

maintainers:
  - name: mikesindieiev
    email: sindieiev@protonmail.ch
    url: https://github.com/directus-labs/helm-chart

version: 2.0.0
appVersion: "11.4.1"

dependencies:
- name: mysql
  version: "~12.2.2"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mysql.enableInstallation
- name: postgresql
  version: "~16.4.9"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enableInstallation
- name: redis
  version: "~20.7.1"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
