apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "directus.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
data:
  DB_CLIENT: {{ .Values.databaseEngine }}
  DB_HOST: {{- if eq .Values.databaseEngine "mysql" }} {{- if .Values.mysql.mysqlURL }} "{{ .Values.mysql.mysqlURL }}" {{- else }} "{{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local" {{- end }} {{- else if eq .Values.databaseEngine "postgresql" }} {{- if .Values.postgresql.postgresqlURL }} "{{ .Values.postgresql.postgresqlURL }}" {{- else }} "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local" {{- end }} {{- end }}
  DB_PORT: {{- if eq .Values.databaseEngine "mysql" }} "3306" {{- else if eq .Values.databaseEngine "postgresql" }} "5432" {{- else }} "" {{- end }}
  DB_DATABASE: {{- if eq .Values.databaseEngine "mysql" }} {{ .Values.mysql.auth.database }} {{- else if eq .Values.databaseEngine "postgresql" }} {{ .Values.postgresql.auth.database }} {{- else }} "" {{- end }}
  DB_USER: {{- if eq .Values.databaseEngine "mysql" }} {{ .Values.mysql.auth.username }} {{- else if eq .Values.databaseEngine "postgresql" }} {{ .Values.postgresql.auth.username }} {{- else }} "" {{- end }}
  ADMIN_EMAIL: "{{ .Values.adminEmail }}"
  REDIS_ENABLED: {{- if .Values.redis.enabled }} "true" {{- else }} "false" {{- end }}
  {{- if .Values.redis.enabled}}
  REDIS_HOST: {{ .Release.Name }}-redis-master
  REDIS_PORT: "6379"
  REDIS_USERNAME: "default"
  {{- end}}
