apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "directus.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
data:
  DB_CLIENT: {{ .Values.databaseEngine }}
  DB_HOST: {{- if .Values.mysql.mysqlURL }} "{{ .Values.mysql.mysqlURL }}" {{- else }} "{{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local" {{- end }}
  DB_PORT: "3306"
  DB_DATABASE: "{{ .Values.mysql.auth.database }}"
  DB_USER: "{{ .Values.mysql.auth.username }}"
  ADMIN_EMAIL: "{{ .Values.adminEmail }}"
  REDIS_ENABLED: {{- if .Values.redis.enabled }} "true" {{- else }} "false" {{- end }}
  {{- if .Values.redis.enabled}}
  REDIS_HOST: {{ .Release.Name }}-redis-master
  REDIS_PORT: "6379"
  REDIS_USERNAME: "default"
  {{- end}}
