{{- if .Values.createMysqlSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.auth.existingSecret }}
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mysql-replication-password: {{ randAlphaNum 10 | b64enc | quote }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
