{{- if .Values.createApplicationSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.applicationSecretName }}
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  SECRET: {{ randAlphaNum 10 | b64enc | quote }}
  KEY: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
